### ISSUE TITLE
_Struct fails when used in a class

### ISSUE THREAD

**Issue by lipkau** [HotKeyIt/_Struct#4]
I am writing a code where I want to get the cursor info. In my code, this is called in a method of a class. Such as:
```
#include lib\ahklib\_Struct.ahk

class foo
{
    __New()
    {}

    Exec()
    {
        POINT := "Long x,Long y"
        mi := new _Struct("DWORD cbSize, DWORD flags, HCURSOR hCursor, POINT ptScreenPos")
        mi.cbSize:=sizeof(mi)
        DllCall("GetCursorInfo", "Ptr", mi[])

        MsgBox % "cbSize:`t`t`t"         mi.cbSize        "`n"
               . "flags:`t`t`t"          mi.flags         "`n"
               . "hCursor:`t`t`t"        mi.hCursor       "`n"
               . "x-coordinate:`t`t"     mi.ptScreenPos.x "`n"
               . "y-coordinate:`t`t"     mi.ptScreenPos.y
    }
}

bar := new foo()
bar.Exec()
```

This **fails**. AHK hangs and I must terminate the process.

However, if I run the same code outside of the class, this works:
```
#include lib\ahklib\_Struct.ahk

POINT := "Long x,Long y"
mi := new _Struct("DWORD cbSize, DWORD flags, HCURSOR hCursor, POINT ptScreenPos")
mi.cbSize:=sizeof(mi)
DllCall("GetCursorInfo", "Ptr", mi[])

MsgBox % "cbSize:`t`t`t"         mi.cbSize        "`n"
       . "flags:`t`t`t"          mi.flags         "`n"
       . "hCursor:`t`t`t"        mi.hCursor       "`n"
       . "x-coordinate:`t`t"     mi.ptScreenPos.x "`n"
       . "y-coordinate:`t`t"     mi.ptScreenPos.y
```

Why is that?

**Comment by HotKeyIt** [comment]
This is because _Struct can only refer to global variable or global object.key:
...
#include lib\ahklib\_Struct.ahk
class foo
{
	static POINT := "Long x,Long y"
    __New()
    {}

    Exec()
    {
        mi := new _Struct("DWORD cbSize, DWORD flags, HCURSOR hCursor, foo.POINT ptScreenPos")
        mi.cbSize:=sizeof(mi)
        DllCall("GetCursorInfo", "Ptr", mi[])

        MsgBox % "cbSize:`t`t`t"         mi.cbSize        "`n"
               . "flags:`t`t`t"          mi.flags         "`n"
               . "hCursor:`t`t`t"        mi.hCursor       "`n"
               . "x-coordinate:`t`t"     mi.ptScreenPos.x "`n"
               . "y-coordinate:`t`t"     mi.ptScreenPos.y
    }
}

bar := new foo()
bar.Exec()
...
